document:
  name: Linee Guida PDND per interoperabilità

  description:
      Linee Guida sull’infrastruttura tecnologica della Piattaforma Digitale Nazionale Dati per l’interoperabilità dei sistemi informativi e delle basi di dati 

  tags:
    - PDND
    - interoperabilità
    - API
    - linee guida
    